spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.MySQL8Dialect

  config:
    activate:
      on-profile: dev

scheduler:
  remittance:
    monthly-cron: "0 0 9 * * *"
    weekly-cron: "0 0 10 * * MON-FRI"

exchange:
  auth-key: ${EX_API_KEY}

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_URL}/api/v2/spans

logging:
  config: classpath:logback-dev.xml
  level:
    org.hibernate.sql: DEBUG
